apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}-deploy
  labels:
    deploy: {{ .Values.image.label }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.label }}
    spec:
      containers:
      - image: "{{ .Values.repository.image }}:{{ .Values.repository.tag }}"
        imagePullPolicy: {{ .Values.repository.pullPolicy }}
        name: {{ .Values.image.name }}
        env:
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sql
                key: sql_user
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql
                key: sql_password
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sql
                key: sql_server
          - name: SQL_DBNAME
            valueFrom:
              secretKeyRef:
                name: sql
                key: sql_dbname
          - name: TRIP_FREQUENCY
            value: "{{ .Values.simulator.tripFrequency }}"
          - name: TEAM_NAME
            value: "{{ .Values.simulator.teamName }}"
		  -	name: SIMULATOR_API_ENDPOINT
			value: "{{ .Values.simulator.apiEndPoint }}"